app = "pace-poc"
primary_region = "sin"

[build]

[env]
  APP_VERSION = "0.1.0"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "15s"
    method = "GET"
    timeout = "2s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"
